inherit_gem:
  rubocop-rails_config:
    - config/rails.yml
require:
  - rubocop-faker
  - rubocop-i18n
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
AllCops:
  Exclude:
    - ".bundle/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "public/packs*/**/*"
    - "tmp/**/*"
    - "vendor/bundle/**/*"
  DisplayCopNames:                true
  NewCops:                        enable
  TargetRubyVersion:              3.0

Layout/LineLength:
  Max:                            120
  Exclude:
  - "bin/bundle"
  - "config/initializers/devise.rb"
Style/FrozenStringLiteralComment:
  EnforcedStyle:                  never

I18n/RailsI18n:
  Enabled:                        true
I18n/GetText:
  Enabled:                        false

Metrics/MethodLength:
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 20
Metrics/AbcSize:
  Include:
    - "app/controllers/*"
    - "app/models/*"
  Max: 50
Metrics/ClassLength:
  Max: 150
Metrics/BlockLength:
  IgnoredMethods: ['describe']
  Max: 30

Style/Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EachForSimpleLoop:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/DefWithParentheses:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: key
Layout/ExtraSpacing:
  AllowForAlignment: false
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
